
---
title: "Exploratory Anaylsis Report"

date: "11/13/2020"

output: html_document
---
```{r echo=FALSE,message=FALSE}
library(knitr)
source("scripts/First Chart.R")
source("scripts/Second Chart.R")
source("scripts/Third Chart.R")
source("scripts/Table of Summary Information.R")
```

```


**Main field/domain:** How different age groups use social media.

**Why are you interested in this field/domain:** It is personal to us, it is how we communicate to people consistently. Social media is something that us as a society uses everyday, regardless of their age. We are intrigued by the differences in how people use social media depending on their age because we know first hand experience the differences in the way we use social media compared to our parents.





[View Dataset](https://raw.githubusercontent.com/info201b-au20/info201-final-group-project/gh-pages/Effects%20of%20Social%20Media%20(Responses).csv)







**Summary paragraph:**




**Chart 1:**
We included this line graph gives us a visual of hours spent on social media per day
and hours spent on physical activity per day for age groups 14-23.
The chart tells us that there is no correlation between the number of hours spent on social media
vs the number of hours spent on physical activity. While the hours on social media line
shows and upward trend (becuase we ordered it that way), the hours of physical activity line is 
unpredictable and sporratic showing no discernible trends or patterns
```{r socialmedia_vs_exercise, echo=FALSE}
plot(socialmedia_vs_exercise)
```

**Chart 2:**
We included the chart to show on average how much time college aged students spend on social media per day
The chart tells us that almost no college aged students (undergrad) spend *NO* time on social media.
The chart also tell us that about two thirds of college aged students (undergrad) spend what we'd call a reasonable
amount of time on social media per day. The other third spend an excessive amount of time on social media
```{r effects, echo=FALSE}
plot(effects)
```

**Chart 3:**
This simple scatter plot gives a precise visual about how different age groups
ranging from 14-23 use social media to communicate. This chart was used to show
the preferred methods of communication because it shows more than one way an
an age group preferred to communicate. This makes it easier to see the trend of
communication between different age groups. The trend of this chart shows that
people between the ages of 18 - 19 prefer all the types of communication methods
while age groups between 14- 16, and 21-3 tend to prefer half or less than half
to communicate. The different preferred types of communication types go up
with age then slowly go back down after the age of 20.

```{r pref_type, echo=FALSE}
plot(pref_type)
```


**Effects of Social Media Table data:**

We decided to display two tables. The first shows the **Mean of Hours** spent and the second shows the **Total Hours** Spent



The table below groups the ages reported and calulates the **mean of hours** spent in each group

```{r echo=FALSE, message=FALSE}
kable(mean_Hours)
```

The table below groups the ages reported and calulates the **total amount** of hours spent in each group 
```{r echo=FALSE, message=FALSE}
kable(total_Hours)
```


